#!/bin/bash
bspc monitor -d 1 2 3 4 5

# Set the border colors.
bspc config normal_border_color \#a9b1d6
bspc config active_border_color \#a9b1d6
bspc config focused_border_color \#ff768c



bspc config border_width        3
bspc config window_gap          6
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.40
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Sxiv state=floating
bspc rule -a Gimp desktop=6 state=fullscreen
bspc rule -a LibreWolf desktop=5 state=monocle
bspc rule -a Save Image state=floating
bspc rule -a mpv state=fullscreen
